version: "3"
services: 
  bb-client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - REACT_APP_ENV=prod
    # env_file:
    #   - ./.env