version: "3"
services: 
  bb-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_ENV=dev
    # env_file:
    #   - ./.env